

<h1 class="page-header">
    <?php echo $bus->id != null ? $bus->Operador : 'Registrar Bus'; ?>
</h1>

<ol class="breadcrumb">
    <li><a href="?i=buses/bus">Camiones</a>/</li>
    <li><a href="http://localhost:7777/Alianza_Fenix_S.A.S/america/index.php">Volver a Alianza Fenix S.A.S</a></li>

    <li class="active"><?php echo $bus->id != null ? $bus->Operador : '/Agregar Nuevo Bus/'; ?></li>

    <li><a href="http://localhost:7777/Alianza_Fenix_S.A.S/america/configuraciones-agregar.php">Ir a configuraciones</a></li>
</ol>


<form id="frm-alumno" action="?au=usuario&a=GuardarUsuario" method="post" enctype="multipart/form-data">
    <input type="hidden" name="id" value="<?php echo $bus->id; ?>" />

    <div class="form-group">
        <label for="Movil">Codigo interno del Bus</label>

        <select name="Movil" class="form-control" required>
            <option selected>Por favor elija El Codigo del bus Correcto</option>
            <option>A001</option>
            <option>A002</option>
            <option>A003</option>
            <option>A004</option>
            <option>A005</option>
            <option>A006</option>
            <option>A007</option>
            <option>A008</option>
            <option>A009</option>
            <option>A010</option>
            <option>A011</option>
            <option>A012</option>
            <option>A013</option>
            <option>A014</option>
            <option>A015</option>
            <option>A016</option>
            <option>A017</option>
            <option>A018</option>
            <option>A019</option>
            <option>A020</option>
            <option>A021</option>
            <option>A022</option>
            <option>A023</option>
            <option>A024</option>
            <option>A025</option>
            <option>A026</option>
            <option>A027</option>
            <option>A028</option>
            <option>A029</option>
            <option>A030</option>
            <option>A031</option>
            <option>A032</option>
            <option>A033</option>
            <option>A034</option>
            <option>A035</option>
            <option>A036</option>
            <option>A037</option>
            <option>A038</option>
            <option>A039</option>
            <option>A040</option>
            <option>A041</option>
            <option>A042</option>
            <option>A043</option>
            <option>A044</option>
            <option>A045</option>
            <option>A046</option>
            <option>A047</option>
            <option>A048</option>
            <option>A049</option>
            <option>A050</option>
            <option>A051</option>
            <option>A052</option>
            <option>A053</option>
            <option>A054</option>
            <option>A055</option>
            <option>A056</option>
            <option>A057</option>
            <option>A058</option>
            <option>A059</option>
            <option>A060</option>
            <option>A061</option>
            <option>A062</option>
            <option>A063</option>
            <option>A064</option>
            <option>A065</option>
            <option>A066</option>
            <option>A067</option>
            <option>A068</option>
            <option>A069</option>
            <option>A070</option>
            <option>A071</option>
            <option>A072</option>
            <option>A073</option>
            <option>A074</option>
            <option>A075</option>
            <option>A076</option>
            <option>A077</option>
            <option>A078</option>
            <option>A079</option>
            <option>A080</option>
            <option>A081</option>
            <option>A082</option>
            <option>A083</option>
            <option>A084</option>
            <option>A085</option>
            <option>A086</option>
            <option>A087</option>
            <option>A088</option>
            <option>A089</option>
            <option>A090</option>
            <option>A091</option>
            <option>A092</option>
            <option>A093</option>
            <option>A094</option>
            <option>A095</option>
            <option>A096</option>
            <option>A097</option>
            <option>A098</option>
            <option>A099</option>
            <option>A100</option>
            <option>A101</option>
            <option>A102</option>
            <option>A103</option>
            <option>A104</option>
            <option>A105</option>
            <option>A106</option>
            <option>A107</option>
            <option>A108</option>
            <option>A109</option>
            <option>A110</option>
            <option>A111</option>
            <option>A112</option>
            <option>A113</option>
            <option>A114</option>
            <option>A115</option>
            <option>A116</option>
            <option>A117</option>
            <option>A118</option>
            <option>A119</option>
            <option>A120</option>
            <option>A121</option>
            <option>A122</option>
            <option>A123</option>
            <option>A124</option>
            <option>A125</option>
            <option>A126</option>
            <option>A127</option>
            <option>A128</option>
            <option>A129</option>
            <option>A130</option>
            <option>A131</option>
            <option>A132</option>
            <option>A133</option>
            <option>A134</option>
            <option>A135</option>
            <option>A136</option>
            <option>A137</option>
            <option>A138</option>
            <option>A139</option>
            <option>A140</option>
            <option>A141</option>
            <option>A142</option>
            <option>A143</option>
            <option>A144</option>
            <option>A145</option>
            <option>A146</option>
            <option>A147</option>
            <option>A148</option>
            <option>A149</option>
            <option>A150</option>
            <option>A151</option>
            <option>A152</option>
            <option>A153</option>
            <option>A154</option>
            <option>A155</option>
            <option>A156</option>
            <option>A157</option>
            <option>A158</option>
            <option>A159</option>
            <option>A160</option>
            <option>A161</option>
            <option>A162</option>
            <option>A163</option>
            <option>A164</option>
            <option>A165</option>
            <option>A166</option>
            <option>A167</option>
            <option>A168</option>
            <option>A169</option>
            <option>A170</option>
            <option>A171</option>
            <option>A172</option>
            <option>A173</option>
            <option>A174</option>
            <option>A175</option>
            <option>A176</option>
            <option>A177</option>
            <option>A178</option>
            <option>A179</option>
            <option>A180</option>
            <option>A181</option>
            <option>A182</option>
            <option>A183</option>
            <option>A184</option>
            <option>A185</option>
            <option>A186</option>
            <option>A187</option>
            <option>B001</option>
            <option>B002</option>
            <option>B003</option>
            <option>B004</option>
            <option>B005</option>
            <option>B006</option>
            <option>B007</option>
            <option>B008</option>
            <option>B009</option>
            <option>B010</option>
            <option>B011</option>
            <option>B012</option>
            <option>B013</option>
            <option>B014</option>
            <option>B015</option>
            <option>B016</option>
            <option>B017</option>
            <option>B018</option>
            <option>B019</option>
            <option>B020</option>
            <option>B021</option>
            <option>B022</option>
            <option>B023</option>
            <option>B024</option>
            <option>B025</option>
            <option>B026</option>
            <option>B027</option>
            <option>B028</option>
            <option>B029</option>
            <option>B030</option>
            <option>B031</option>
            <option>B032</option>
            <option>B033</option>
            <option>B034</option>
            <option>B035</option>
            <option>B036</option>
            <option>B037</option>
            <option>B038</option>
            <option>B039</option>
            <option>B040</option>
            <option>B041</option>
            <option>B042</option>
            <option>B043</option>
            <option>B044</option>
            <option>B045</option>
            <option>B046</option>
            <option>B047</option>
            <option>B048</option>
            <option>B049</option>
            <option>B050</option>
            <option>B051</option>
            <option>B052</option>
            <option>B053</option>
            <option>B054</option>
            <option>B055</option>
            <option>B056</option>
            <option>B057</option>
            <option>B058</option>
            <option>B059</option>
            <option>B060</option>
            <option>B061</option>
            <option>B062</option>
            <option>B063</option>
            <option>B064</option>
            <option>B065</option>
            <option>B066</option>
            <option>B067</option>
            <option>B068</option>
            <option>B069</option>
            <option>B070</option>
            <option>B071</option>
            <option>B072</option>
            <option>B073</option>
            <option>B074</option>
            <option>B075</option>
            <option>B076</option>
            <option>B077</option>
            <option>B078</option>
            <option>B079</option>
            <option>B080</option>
            <option>B081</option>
            <option>B082</option>
            <option>B083</option>
            <option>B084</option>
            <option>B085</option>
            <option>B086</option>
            <option>B087</option>
            <option>B088</option>
            <option>B089</option>
            <option>B090</option>
            <option>B091</option>
            <option>B092</option>
            <option>B093</option>
            <option>B094</option>
            <option>B095</option>
            <option>B096</option>
            <option>B097</option>
            <option>B098</option>
            <option>B099</option>
            <option>B100</option>
            <option>B101</option>
            <option>B102</option>
            <option>B103</option>
            <option>B104</option>
            <option>B105</option>
            <option>B106</option>
            <option>B107</option>
            <option>B108</option>
            <option>B109</option>
            <option>B110</option>
            <option>B111</option>
            <option>B112</option>
            <option>B113</option>
            <option>B114</option>
            <option>B115</option>
            <option>B116</option>
            <option>B117</option>
            <option>B118</option>
            <option>B119</option>
            <option>B120</option>
            <option>B121</option>
            <option>B122</option>
            <option>B123</option>
            <option>B124</option>
            <option>B125</option>
            <option>B126</option>
            <option>B127</option>
            <option>B128</option>
            <option>B129</option>
            <option>B130</option>
            <option>B131</option>
            <option>B132</option>
            <option>B133</option>
            <option>B134</option>
            <option>B135</option>
            <option>B136</option>
            <option>B137</option>
            <option>B138</option>
            <option>B139</option>
            <option>B140</option>
            <option>B141</option>
            <option>B142</option>
            <option>B143</option>
            <option>B144</option>
            <option>B145</option>
            <option>B146</option>
            <option>B147</option>
            <option>B148</option>
            <option>B149</option>
            <option>B150</option>
            <option>B151</option>
            <option>B152</option>
            <option>B153</option>
            <option>B154</option>
            <option>B155</option>
            <option>B156</option>
            <option>B157</option>
            <option>B158</option>
            <option>B159</option>
            <option>B160</option>
            <option>B161</option>
            <option>B162</option>
            <option>B163</option>
            <option>B164</option>
            <option>B165</option>
            <option>B166</option>
            <option>B167</option>
            <option>B168</option>
            <option>B169</option>
            <option>B170</option>
            <option>B171</option>
            <option>B172</option>
            <option>B173</option>
            <option>B174</option>
            <option>B175</option>
            <option>B176</option>
            <option>B177</option>
            <option>B178</option>
            <option>B179</option>
            <option>B180</option>
            <option>B181</option>
            <option>B182</option>
            <option>B183</option>
            <option>B184</option>
            <option>B185</option>
            <option>B186</option>
            <option>B187</option>
            <option>B188</option>
            <option>B189</option>
            <option>B190</option>
            <option>B191</option>
            <option>B192</option>
            <option>B193</option>
            <option>B194</option>
            <option>B195</option>
            <option>B196</option>
            <option>B197</option>
            <option>B198</option>
            <option>B199</option>
            <option>B200</option>
            <option>B201</option>
            <option>B202</option>
            <option>B203</option>
            <option>B204</option>
            <option>B205</option>
            <option>B206</option>
            <option>B207</option>
            <option>B208</option>
            <option>B209</option>
            <option>D001</option>
            <option>D002</option>
            <option>D003</option>
            <option>D004</option>
            <option>D005</option>
            <option>D006</option>
            <option>D007</option>
            <option>D008</option>
            <option>D009</option>
            <option>D010</option>
            <option>D011</option>
            <option>D012</option>
            <option>D013</option>
            <option>D014</option>
            <option>D015</option>
            <option>D016</option>
            <option>D017</option>
            <option>D018</option>
            <option>D019</option>
            <option>D020</option>
            <option>D021</option>
            <option>D022</option>
            <option>D023</option>
            <option>D024</option>
            <option>D025</option>
            <option>D026</option>
            <option>D027</option>
            <option>D028</option>
            <option>D029</option>
            <option>D030</option>
            <option>D031</option>
            <option>D032</option>
            <option>D033</option>
            <option>D034</option>
            <option>D035</option>
            <option>D036</option>
            <option>D037</option>
            <option>D038</option>
            <option>D039</option>
            <option>D040</option>
            <option>D041</option>
            <option>D042</option>
            <option>D043</option>
            <option>D044</option>
            <option>D045</option>
            <option>D100</option>
            <option>D101</option>
            <option>D102</option>
            <option>D103</option>
            <option>D104</option>
            <option>D105</option>
            <option>D106</option>
            <option>D107</option>
            <option>D108</option>
            <option>D109</option>
            <option>D110</option>
            <option>D111</option>
            <option>D112</option>
            <option>D113</option>
            <option>D114</option>
            <option>D115</option>
            <option>D116</option>
            <option>D117</option>
            <option>D118</option>
            <option>D119</option>
            <option>D120</option>
            <option>D121</option>
            <option>D122</option>
            <option>D123</option>
            <option>D124</option>
            <option>D125</option>
            <option>D126</option>
            <option>D127</option>
            <option>D128</option>
            <option>D129</option>
            <option>D130</option>
            <option>D131</option>
            <option>D132</option>
            <option>D133</option>
            <option>D134</option>
            <option>D135</option>
            <option>D136</option>
            <option>D137</option>
            <option>D138</option>
            <option>D139</option>
            <option>D140</option>
            <option>D141</option>
            <option>D142</option>
            <option>D143</option>
            <option>D144</option>
            <option>D145</option>
            <option>D146</option>
            <option>D147</option>
            <option>D148</option>
            <option>D149</option>
            <option>D150</option>
            <option>D151</option>
            <option>D152</option>
            <option>D153</option>
            <option>D154</option>
            <option>D155</option>
            <option>D156</option>
            <option>D157</option>
            <option>D158</option>
            <option>D159</option>
            <option>D160</option>
            <option>D161</option>
            <option>D162</option>
            <option>D163</option>
            <option>D164</option>
            <option>D165</option>
            <option>D166</option>
            <option>D167</option>
            <option>D168</option>
            <option>D169</option>
            <option>D170</option>
            <option>D171</option>
            <option>D172</option>
            <option>D173</option>
            <option>D174</option>
            <option>D175</option>
            <option>D176</option>
            <option>D177</option>
            <option>D178</option>
            <option>D179</option>
            <option>D180</option>
            <option>D181</option>
            <option>D182</option>
            <option>D183</option>
            <option>D184</option>
            <option>D185</option>
            <option>D186</option>
            <option>D187</option>
            <option>D188</option>
            <option>D189</option>
            <option>D190</option>
            <option>D191</option>
            <option>D192</option>
            <option>D193</option>
            <option>D194</option>
            <option>D195</option>
            <option>D196</option>
            <option>D197</option>
            <option>D198</option>
            <option>D199</option>
            <option>D200</option>
            <option>D201</option>
            <option>D202</option>
            <option>D203</option>
            <option>D204</option>
            <option>D205</option>
            <option>D206</option>
            <option>D207</option>
            <option>D208</option>
            <option>D209</option>
            <option>D210</option>
            <option>D211</option>
            <option>D212</option>
            <option>D213</option>
            <option>D214</option>
            <option>D215</option>
            <option>D216</option>
            <option>D217</option>
            <option>D218</option>
            <option>D219</option>
            <option>D220</option>
            <option>D221</option>
            <option>D222</option>
            <option>D223</option>
            <option>D224</option>
            <option>D225</option>
            <option>D226</option>
            <option>D227</option>
            <option>D228</option>
            <option>D229</option>
            <option>D230</option>
            <option>D231</option>
            <option>D232</option>
            <option>D233</option>
            <option>D234</option>
            <option>D500</option>
            <option>D501</option>
            <option>D502</option>
            <option>D503</option>
            <option>D504</option>
            <option>D505</option>
            <option>D506</option>
            <option>D507</option>
            <option>D508</option>
            <option>D509</option>
            <option>D510</option>
            <option>D511</option>
            <option>D512</option>
            <option>D513</option>
            <option>D514</option>
            <option>D515</option>
            <option>D516</option>
            <option>D517</option>
            <option>D518</option>
            <option>D519</option>
            <option>D520</option>
            <option>D521</option>
            <option>D522</option>
            <option>D523</option>
            <option>D524</option>
            <option>D525</option>
            <option>D526</option>
            <option>D527</option>
            <option>D528</option>
            <option>D529</option>
            <option>D530</option>
            <option>D531</option>
            <option>D532</option>
            <option>D533</option>
            <option>D534</option>
            <option>D535</option>
            <option>D536</option>
            <option>D537</option>
            <option>D538</option>
            <option>D539</option>
            <option>D540</option>
            <option>D541</option>
            <option>D542</option>
            <option>D543</option>
            <option>D544</option>
            <option>D545</option>
            <option>D546</option>
            <option>D547</option>
            <option>D548</option>
            <option>D549</option>
            <option>D550</option>
            <option>D551</option>
            <option>D552</option>
            <option>D553</option>
            <option>D554</option>
            <option>D555</option>
            <option>D556</option>
            <option>D557</option>
            <option>D558</option>
            <option>D559</option>
            <option>D560</option>
            <option>D561</option>
            <option>D562</option>
            <option>D563</option>
            <option>D564</option>
            <option>D565</option>
            <option>D566</option>
            <option>D567</option>
            <option>D568</option>
            <option>D569</option>
            <option>D570</option>
            <option>D571</option>
            <option>D572</option>
            <option>D573</option>
            <option>D574</option>
            <option>D575</option>
            <option>D576</option>
            <option>D577</option>
            <option>D578</option>
            <option>D579</option>
            <option>D580</option>
            <option>D581</option>
            <option>D582</option>
            <option>D583</option>
            <option>D584</option>
            <option>D585</option>
            <option>D586</option>
            <option>D587</option>
            <option>D588</option>
            <option>D589</option>
            <option>D590</option>
            <option>D591</option>
            <option>D592</option>
            <option>E001</option>
            <option>E002</option>
            <option>E003</option>
            <option>E004</option>
            <option>E005</option>
            <option>E006</option>
            <option>E007</option>
            <option>E008</option>
            <option>E009</option>
            <option>E010</option>
            <option>E011</option>
            <option>E012</option>
            <option>E013</option>
            <option>E014</option>
            <option>E015</option>
            <option>E016</option>
            <option>E017</option>
            <option>E018</option>
            <option>E019</option>
            <option>E020</option>
            <option>E021</option>
            <option>E022</option>
            <option>E023</option>
            <option>E024</option>
            <option>E025</option>
            <option>E026</option>
            <option>E027</option>
            <option>E028</option>
            <option>E029</option>
            <option>E030</option>
            <option>E031</option>
            <option>E032</option>
            <option>E033</option>
            <option>E034</option>
            <option>E035</option>
            <option>E036</option>
            <option>E037</option>
            <option>E038</option>
            <option>E039</option>
            <option>E040</option>
            <option>E041</option>
            <option>E042</option>
            <option>E043</option>
            <option>E044</option>
            <option>E045</option>
            <option>E046</option>
            <option>E047</option>
            <option>E048</option>
            <option>E049</option>
            <option>E050</option>
            <option>E051</option>
            <option>E052</option>
            <option>E053</option>
            <option>E054</option>
            <option>E055</option>
            <option>E056</option>
            <option>E057</option>
            <option>E058</option>
            <option>E059</option>
            <option>E060</option>
            <option>E061</option>
            <option>E062</option>
            <option>E063</option>
            <option>E064</option>
            <option>E065</option>
            <option>E066</option>
            <option>E067</option>
            <option>E068</option>
            <option>E069</option>
            <option>E070</option>
            <option>E071</option>
            <option>E072</option>
            <option>E073</option>
            <option>E074</option>
            <option>E075</option>
            <option>E076</option>
            <option>E077</option>
            <option>E078</option>
            <option>E079</option>
            <option>E080</option>
            <option>E081</option>
            <option>E082</option>
            <option>E083</option>
            <option>E084</option>
            <option>E085</option>
            <option>E086</option>
            <option>E087</option>
            <option>E088</option>
            <option>E089</option>
            <option>E090</option>
            <option>E091</option>
            <option>E092</option>
            <option>E093</option>
            <option>E094</option>
            <option>E095</option>
            <option>E096</option>
            <option>E097</option>
            <option>E098</option>
            <option>E099</option>
            <option>E100</option>
            <option>E101</option>
            <option>E102</option>
            <option>E103</option>
            <option>E104</option>
            <option>E105</option>
            <option>E106</option>
            <option>E107</option>
            <option>E108</option>
            <option>E109</option>
            <option>E110</option>
            <option>E111</option>
            <option>E112</option>
            <option>E113</option>
            <option>E114</option>
            <option>E115</option>
            <option>E116</option>
            <option>E117</option>
            <option>E118</option>
            <option>E119</option>
            <option>E120</option>
            <option>E121</option>
            <option>E122</option>
            <option>E123</option>
            <option>E124</option>
            <option>E700</option>
            <option>E701</option>
            <option>E702</option>
            <option>E703</option>
            <option>E704</option>
            <option>E705</option>
            <option>E706</option>
            <option>E707</option>
            <option>E708</option>
            <option>E709</option>
            <option>E710</option>
            <option>E711</option>
            <option>E712</option>
            <option>E713</option>
            <option>E714</option>
            <option>E715</option>
            <option>E716</option>
            <option>E717</option>
            <option>E718</option>
            <option>E719</option>
            <option>E720</option>
            <option>E721</option>
            <option>E722</option>
            <option>E723</option>
            <option>E724</option>
            <option>E725</option>
            <option>E726</option>
            <option>E727</option>
            <option>E728</option>
            <option>E729</option>
            <option>E730</option>
            <option>E731</option>
            <option>E732</option>
            <option>E733</option>
            <option>E734</option>
            <option>E735</option>
            <option>E736</option>
            <option>E737</option>
            <option>E738</option>
            <option>E739</option>
            <option>E740</option>
            <option>E741</option>
            <option>E742</option>
            <option>E743</option>
            <option>E744</option>
            <option>E745</option>
            <option>E746</option>
            <option>E747</option>
            <option>E748</option>
            <option>E749</option>
            <option>E750</option>
            <option>E751</option>
            <option>E752</option>
            <option>E753</option>
            <option>E754</option>
            <option>E755</option>
            <option>E756</option>
            <option>E757</option>
            <option>E758</option>
            <option>E759</option>
            <option>E760</option>
            <option>E761</option>
            <option>E762</option>
            <option>E763</option>
            <option>E764</option>
            <option>E765</option>
            <option>E766</option>
            <option>E767</option>
            <option>E768</option>
            <option>E769</option>
            <option>E770</option>
            <option>E771</option>
            <option>E772</option>
            <option>E773</option>
            <option>E774</option>
            <option>E775</option>
            <option>E776</option>
            <option>E777</option>
            <option>E778</option>
            <option>E779</option>
            <option>E780</option>
            <option>E781</option>
            <option>E782</option>
            <option>E783</option>
            <option>E784</option>
            <option>E785</option>
            <option>E786</option>
            <option>E787</option>
            <option>E788</option>
            <option>E789</option>
            <option>E790</option>
            <option>E791</option>
            <option>E792</option>
            <option>M001</option>
            <option>M002</option>
            <option>M003</option>
            <option>M004</option>
            <option>M005</option>
            <option>M006</option>
            <option>M007</option>
            <option>M008</option>
            <option>M009</option>
            <option>M010</option>
            <option>M011</option>
            <option>M012</option>
            <option>M013</option>
            <option>M014</option>
            <option>M015</option>
            <option>M016</option>
            <option>M017</option>
            <option>M018</option>
            <option>M019</option>
            <option>M020</option>
            <option>M021</option>
            <option>M022</option>
            <option>M023</option>
            <option>M024</option>
            <option>M025</option>
            <option>M026</option>
            <option>M027</option>
            <option>M028</option>
            <option>M029</option>
            <option>M030</option>
            <option>M031</option>
            <option>M032</option>
            <option>M033</option>
            <option>M034</option>
            <option>M035</option>
            <option>M036</option>
            <option>M037</option>
            <option>M038</option>
            <option>M039</option>
            <option>M040</option>
            <option>M041</option>
            <option>M042</option>
            <option>M043</option>
            <option>M044</option>
            <option>M045</option>
            <option>M046</option>
            <option>M047</option>
            <option>M048</option>
            <option>M049</option>
            <option>M050</option>
            <option>M051</option>
            <option>M052</option>
            <option>M053</option>
            <option>M054</option>
            <option>M055</option>
            <option>M056</option>
            <option>M057</option>
            <option>M058</option>
            <option>M059</option>
            <option>M060</option>
            <option>M061</option>
            <option>M062</option>
            <option>M063</option>
            <option>M064</option>
            <option>M065</option>
            <option>M066</option>
            <option>M067</option>
            <option>M068</option>
            <option>M069</option>
            <option>M070</option>
            <option>M071</option>
            <option>M072</option>
            <option>M073</option>
            <option>M074</option>
            <option>M075</option>
            <option>M076</option>
            <option>M077</option>
            <option>M078</option>
            <option>M079</option>
            <option>M080</option>
            <option>M081</option>
            <option>M082</option>
            <option>M083</option>
            <option>M084</option>
            <option>M085</option>
            <option>M086</option>
            <option>M087</option>
            <option>M088</option>
            <option>M089</option>
            <option>M090</option>
            <option>M091</option>
            <option>M092</option>
            <option>M093</option>
            <option>M094</option>
            <option>M095</option>
            <option>M096</option>
            <option>M097</option>
            <option>M098</option>
            <option>M099</option>
            <option>M100</option>
            <option>M101</option>
            <option>M102</option>
            <option>M103</option>
            <option>M104</option>
            <option>M105</option>
            <option>M106</option>
            <option>M107</option>
            <option>M108</option>
            <option>M109</option>
            <option>M110</option>
            <option>M111</option>
            <option>M112</option>
            <option>M113</option>
            <option>M114</option>
            <option>M115</option>
            <option>M116</option>
            <option>M117</option>
            <option>M118</option>
            <option>M119</option>
            <option>M120</option>
            <option>M121</option>
            <option>M122</option>
            <option>M123</option>
            <option>M124</option>
            <option>M125</option>
            <option>M126</option>
            <option>M127</option>
            <option>M128</option>
            <option>M129</option>
            <option>M130</option>
            <option>M131</option>
            <option>M132</option>
            <option>M133</option>
            <option>M134</option>
            <option>M135</option>
            <option>M136</option>
            <option>M137</option>
            <option>M138</option>
            <option>M139</option>
            <option>M140</option>
            <option>M141</option>
            <option>M142</option>
            <option>M143</option>
            <option>M144</option>
            <option>M145</option>
            <option>M146</option>
            <option>M147</option>
            <option>M148</option>
            <option>M149</option>
            <option>M150</option>
            <option>M151</option>
            <option>M152</option>
            <option>M153</option>
            <option>M154</option>
            <option>M155</option>
            <option>M156</option>
            <option>M157</option>
            <option>M158</option>
            <option>M159</option>
            <option>M160</option>
            <option>M161</option>
            <option>M162</option>
            <option>M163</option>
            <option>M164</option>
            <option>M165</option>
            <option>M166</option>
            <option>M167</option>
            <option>M168</option>
            <option>M169</option>
            <option>M170</option>
            <option>M171</option>
            <option>M172</option>
            <option>M173</option>
            <option>M174</option>
            <option>M175</option>
            <option>M176</option>
            <option>M177</option>
            <option>M178</option>
            <option>M179</option>
            <option>M180</option>
            <option>M181</option>
            <option>M182</option>
            <option>M183</option>
            <option>M184</option>
            <option>M185</option>
            <option>M186</option>
            <option>M187</option>
            <option>M188</option>
            <option>M189</option>
            <option>M190</option>
            <option>M191</option>
            <option>M192</option>
            <option>M193</option>
            <option>K001</option>
            <option>K002</option>
            <option>K003</option>
            <option>K004</option>
            <option>K005</option>
            <option>K006</option>
            <option>K007</option>
            <option>K008</option>
            <option>K009</option>
            <option>K010</option>
            <option>K011</option>
            <option>K012</option>
            <option>K013</option>
            <option>K014</option>
            <option>K015</option>
            <option>K016</option>
            <option>K017</option>
            <option>K018</option>
            <option>K019</option>
            <option>K020</option>
            <option>K021</option>
            <option>K022</option>
            <option>K023</option>
            <option>K024</option>
            <option>K025</option>
            <option>K026</option>
            <option>K027</option>
            <option>K028</option>
            <option>K029</option>
            <option>K030</option>
            <option>K031</option>
            <option>K032</option>
            <option>K033</option>
            <option>K034</option>
            <option>K035</option>
            <option>K036</option>
            <option>K037</option>
            <option>K038</option>
            <option>K039</option>
            <option>K040</option>
            <option>K041</option>
            <option>K042</option>
            <option>K043</option>
            <option>K044</option>
            <option>K045</option>
            <option>K046</option>
            <option>K047</option>
            <option>K048</option>
            <option>K049</option>
            <option>K050</option>
            <option>K051</option>
            <option>K052</option>
            <option>K053</option>
            <option>K054</option>
            <option>K055</option>
            <option>K056</option>
            <option>K057</option>
            <option>K058</option>
            <option>K059</option>
            <option>K060</option>
            <option>K061</option>
            <option>K062</option>
            <option>K063</option>
            <option>K064</option>
            <option>K065</option>
            <option>K066</option>
            <option>K067</option>
            <option>K068</option>
            <option>K069</option>
            <option>K070</option>
            <option>K071</option>
            <option>K072</option>
            <option>K073</option>
            <option>K074</option>
            <option>K075</option>
            <option>K076</option>
            <option>K077</option>
            <option>K078</option>
            <option>K079</option>
            <option>K080</option>
            <option>K081</option>
            <option>K082</option>
            <option>K083</option>
            <option>K084</option>
            <option>K085</option>
            <option>K086</option>
            <option>K087</option>
            <option>K088</option>
            <option>K089</option>
            <option>K090</option>
            <option>K091</option>
            <option>K092</option>
            <option>K093</option>
            <option>K094</option>
            <option>K095</option>
            <option>K096</option>
            <option>K097</option>
            <option>K098</option>
            <option>K099</option>
            <option>K100</option>
            <option>K101</option>
            <option>K102</option>
            <option>K103</option>
            <option>K104</option>
            <option>K105</option>
            <option>K106</option>
            <option>K107</option>
            <option>K108</option>
            <option>K109</option>
            <option>K110</option>
            <option>K111</option>
            <option>K112</option>
            <option>K113</option>
            <option>K114</option>
            <option>K115</option>
            <option>K116</option>
            <option>K117</option>
            <option>K118</option>
            <option>K119</option>
            <option>K120</option>
            <option>K121</option>
            <option>K122</option>
            <option>K123</option>
            <option>K124</option>
            <option>K125</option>
            <option>K126</option>
            <option>K127</option>
            <option>K128</option>
            <option>K129</option>
            <option>K130</option>
            <option>K131</option>
            <option>K132</option>
            <option>K133</option>
            <option>K134</option>
            <option>K135</option>
            <option>K136</option>
            <option>K137</option>
            <option>K138</option>
            <option>K139</option>
            <option>K140</option>
            <option>K141</option>
            <option>K142</option>
            <option>K143</option>
            <option>K144</option>
            <option>K145</option>
            <option>K146</option>
            <option>K147</option>
            <option>K148</option>
            <option>K149</option>
            <option>K150</option>
            <option>K151</option>
            <option>K152</option>
            <option>K153</option>
            <option>K154</option>
            <option>K155</option>
            <option>K156</option>
            <option>K157</option>
            <option>K158</option>
            <option>K159</option>
            <option>K160</option>
            <option>K161</option>
            <option>K162</option>
            <option>K163</option>
            <option>K164</option>
            <option>K165</option>
            <option>K166</option>
            <option>K167</option>
            <option>K168</option>
            <option>K169</option>
            <option>K170</option>
            <option>K171</option>
            <option>N001</option>
            <option>N002</option>
            <option>N003</option>
            <option>N004</option>
            <option>N005</option>
            <option>N006</option>
            <option>N007</option>
            <option>N008</option>
            <option>N009</option>
            <option>N010</option>
            <option>N011</option>
            <option>N012</option>
            <option>N013</option>
            <option>N014</option>
            <option>N015</option>
            <option>N016</option>
            <option>N017</option>
            <option>N018</option>
            <option>N019</option>
            <option>N020</option>
            <option>N021</option>
            <option>N022</option>
            <option>N023</option>
            <option>N024</option>
            <option>N025</option>
            <option>N026</option>
            <option>N027</option>
            <option>N028</option>
            <option>N029</option>
            <option>N030</option>
            <option>N031</option>
            <option>N032</option>
            <option>N033</option>
            <option>N034</option>
            <option>N035</option>
            <option>N100</option>
            <option>N101</option>
            <option>N102</option>
            <option>N103</option>
            <option>N104</option>
            <option>N105</option>
            <option>N106</option>
            <option>N107</option>
            <option>N108</option>
            <option>N109</option>
            <option>N110</option>
            <option>N111</option>
            <option>N112</option>
            <option>N113</option>
            <option>N114</option>
            <option>N115</option>
            <option>N116</option>
            <option>N117</option>
            <option>N118</option>
            <option>N119</option>
            <option>N120</option>
            <option>N121</option>
            <option>N122</option>
            <option>N123</option>
            <option>N124</option>
            <option>N125</option>
            <option>N126</option>
            <option>N127</option>
            <option>N128</option>
            <option>N129</option>
            <option>N130</option>
            <option>N131</option>
            <option>N132</option>
            <option>N133</option>
            <option>N134</option>
            <option>N135</option>
            <option>N136</option>
            <option>N137</option>
            <option>N138</option>
            <option>N139</option>
            <option>N140</option>
            <option>N141</option>
            <option>N142</option>
            <option>N143</option>
            <option>N144</option>
            <option>N145</option>
            <option>N146</option>
            <option>N147</option>
            <option>N148</option>
            <option>N149</option>
            <option>N150</option>
            <option>N151</option>
            <option>N152</option>
            <option>N153</option>
            <option>N154</option>
            <option>N155</option>
            <option>N156</option>
            <option>N157</option>
            <option>N158</option>
            <option>N159</option>
            <option>N160</option>
            <option>N161</option>
            <option>N162</option>
            <option>N163</option>
            <option>N164</option>
            <option>N165</option>
            <option>N166</option>
            <option>N167</option>
            <option>N168</option>
            <option>N169</option>
            <option>N170</option>
            <option>N171</option>
            <option>N172</option>
            <option>N173</option>
            <option>N174</option>
            <option>N175</option>
            <option>N176</option>
            <option>N177</option>
            <option>N178</option>
            <option>N179</option>
            <option>N180</option>
            <option>N181</option>
            <option>N182</option>
            <option>N183</option>
            <option>N184</option>
            <option>N185</option>
            <option>N186</option>
            <option>N187</option>
            <option>N188</option>
            <option>N189</option>
            <option>N190</option>
            <option>N191</option>
            <option>N192</option>
            <option>N500</option>
            <option>N501</option>
            <option>N502</option>
            <option>N503</option>
            <option>N504</option>
            <option>N505</option>
            <option>N506</option>
            <option>N507</option>
            <option>N508</option>
            <option>N509</option>
            <option>N510</option>
            <option>N511</option>
            <option>N512</option>
            <option>N513</option>
            <option>N514</option>
            <option>N515</option>
            <option>N516</option>
            <option>N517</option>
            <option>N518</option>
            <option>N519</option>
            <option>N520</option>
            <option>N521</option>
            <option>N522</option>
            <option>N523</option>
            <option>N524</option>
            <option>N525</option>
            <option>N526</option>
            <option>N527</option>
            <option>N528</option>
            <option>N529</option>
            <option>N530</option>
            <option>N531</option>
            <option>N532</option>
            <option>N533</option>
            <option>N534</option>
            <option>N535</option>
            <option>N536</option>
            <option>N537</option>
            <option>N538</option>
            <option>N539</option>
            <option>N540</option>
            <option>N541</option>
            <option>N542</option>
            <option>N543</option>
            <option>N544</option>
            <option>N545</option>
            <option>N546</option>
            <option>N547</option>
            <option>N548</option>
            <option>N549</option>
            <option>N550</option>
            <option>N551</option>
            <option>N552</option>
            <option>N553</option>
            <option>N554</option>
            <option>N555</option>
            <option>N556</option>
            <option>N557</option>
            <option>N558</option>
            <option>N559</option>
            <option>N560</option>
            <option>N561</option>
            <option>N562</option>
            <option>N563</option>
            <option>N564</option>
            <option>N565</option>
            <option>N566</option>
            <option>N567</option>
            <option>N568</option>
            <option>N569</option>
            <option>N570</option>
            <option>N571</option>
            <option>N572</option>
            <option>N573</option>
            <option>N574</option>
            <option>N575</option>
            <option>N576</option>
            <option>N577</option>
            <option>N578</option>
            <option>N579</option>
            <option>N580</option>
            <option>N581</option>
            <option>N582</option>
            <option>N583</option>
            <option>N584</option>
            <option>N585</option>
            <option>N586</option>
            <option>N587</option>
            <option>N588</option>
            <option>N589</option>
            <option>N590</option>
            <option>N591</option>
            <option>N592</option>
            <option>N593</option>
            <option>N594</option>
            <option>N595</option>
            <option>N596</option>
            <option>N597</option>
            <option>N598</option>
            <option>N599</option>
            <option>N600</option>
            <option>N601</option>
            <option>N602</option>
            <option>N603</option>
            <option>N604</option>
            <option>N605</option>
            <option>N606</option>
            <option>N607</option>
            <option>N608</option>
            <option>N609</option>
            <option>N610</option>
            <option>N611</option>
            <option>N612</option>
            <option>N613</option>
            <option>N614</option>
            <option>N615</option>
            <option>N616</option>
            <option>N617</option>
            <option>N618</option>
            <option>N619</option>
            <option>N620</option>
            <option>N621</option>
            <option>N622</option>
            <option>N623</option>
            <option>N624</option>
            <option>N625</option>
            <option>N626</option>
            <option>N627</option>
            <option>N628</option>
            <option>N629</option>
            <option>N630</option>
            <option>T001</option>
            <option>T002</option>
            <option>T003</option>
            <option>T004</option>
            <option>T005</option>
            <option>T006</option>
            <option>T007</option>
            <option>T008</option>
            <option>T009</option>
            <option>T010</option>
            <option>T011</option>
            <option>T012</option>
            <option>T013</option>
            <option>T014</option>
            <option>T015</option>
            <option>T016</option>
            <option>T017</option>
            <option>T018</option>
            <option>T019</option>
            <option>T020</option>
            <option>T021</option>
            <option>T022</option>
            <option>T023</option>
            <option>T024</option>
            <option>T025</option>
            <option>T026</option>
            <option>T027</option>
            <option>T028</option>
            <option>T029</option>
            <option>T030</option>
            <option>T031</option>
            <option>T032</option>
            <option>T033</option>
            <option>T034</option>
            <option>T035</option>
            <option>T036</option>
            <option>T037</option>
            <option>T038</option>
            <option>T039</option>
            <option>T040</option>
            <option>T041</option>
            <option>T042</option>
            <option>T043</option>
            <option>T044</option>
            <option>T045</option>
            <option>T046</option>
            <option>T047</option>
            <option>T048</option>
            <option>T049</option>
            <option>T050</option>
            <option>T051</option>
            <option>T052</option>
            <option>T053</option>
            <option>T054</option>
            <option>T055</option>
            <option>T056</option>
            <option>T057</option>
            <option>T058</option>
            <option>T059</option>
            <option>T060</option>
            <option>T061</option>
            <option>T062</option>
            <option>T063</option>
            <option>T064</option>
            <option>T065</option>
            <option>T066</option>
            <option>T067</option>
            <option>T068</option>
            <option>T069</option>
            <option>T070</option>
            <option>T071</option>
            <option>T072</option>
            <option>T073</option>
            <option>T074</option>
            <option>T075</option>
            <option>T076</option>
            <option>T077</option>
            <option>T078</option>
            <option>T079</option>
            <option>T080</option>
            <option>T081</option>
            <option>T082</option>
            <option>T083</option>
            <option>T084</option>
            <option>T085</option>
            <option>T086</option>
            <option>T087</option>
            <option>T088</option>
            <option>T089</option>
            <option>T090</option>
            <option>T091</option>
            <option>T092</option>
            <option>T093</option>
            <option>T094</option>
            <option>T095</option>
            <option>T096</option>
            <option>T097</option>
            <option>T098</option>
            <option>T099</option>
            <option>T100</option>
            <option>T101</option>
            <option>T102</option>
            <option>T103</option>
            <option>T104</option>
            <option>T105</option>
            <option>T106</option>
            <option>T107</option>
            <option>T108</option>
            <option>T109</option>
            <option>T110</option>
            <option>T111</option>
            <option>T112</option>
            <option>T113</option>
            <option>T114</option>
            <option>T115</option>
            <option>T116</option>
            <option>T117</option>
            <option>T118</option>
            <option>T119</option>
            <option>T120</option>
            <option>T121</option>
            <option>T122</option>
            <option>T123</option>
            <option>T124</option>
            <option>T125</option>
            <option>T126</option>
            <option>T127</option>
            <option>T128</option>
            <option>T129</option>
            <option>T130</option>
            <option>T131</option>
            <option>T132</option>
            <option>T133</option>
            <option>T134</option>
            <option>T135</option>
            <option>T136</option>
            <option>T137</option>
            <option>T138</option>
            <option>T139</option>
            <option>T140</option>
            <option>T141</option>
            <option>T142</option>
            <option>S001</option>
            <option>S002</option>
            <option>S003</option>
            <option>S004</option>
            <option>S005</option>
            <option>S006</option>
            <option>S007</option>
            <option>S008</option>
            <option>S009</option>
            <option>S010</option>
            <option>S011</option>
            <option>S012</option>
            <option>S013</option>
            <option>S014</option>
            <option>S015</option>
            <option>S016</option>
            <option>S017</option>
            <option>S018</option>
            <option>S019</option>
            <option>S020</option>
            <option>S021</option>
            <option>S022</option>
            <option>S023</option>
            <option>S024</option>
            <option>S025</option>
            <option>S026</option>
            <option>S027</option>
            <option>S028</option>
            <option>S029</option>
            <option>S030</option>
            <option>S031</option>
            <option>S032</option>
            <option>S033</option>
            <option>S034</option>
            <option>S035</option>
            <option>S036</option>
            <option>S037</option>
            <option>S038</option>
            <option>S039</option>
            <option>S040</option>
            <option>S041</option>
            <option>S042</option>
            <option>S043</option>
            <option>S044</option>
            <option>S045</option>
            <option>S046</option>
            <option>S047</option>
            <option>S048</option>
            <option>S049</option>
            <option>S050</option>
            <option>S051</option>
            <option>S052</option>
            <option>S053</option>
            <option>S054</option>
            <option>S055</option>
            <option>S056</option>
            <option>S057</option>
            <option>S058</option>
            <option>S059</option>
            <option>S060</option>
            <option>S061</option>
            <option>S062</option>
            <option>S063</option>
            <option>S064</option>
            <option>S065</option>
            <option>S066</option>
            <option>S067</option>
            <option>S068</option>
            <option>S069</option>
            <option>S070</option>
            <option>S071</option>
            <option>S072</option>
            <option>S073</option>
            <option>S074</option>
            <option>S075</option>
            <option>S076</option>
            <option>S077</option>
            <option>S078</option>
            <option>S079</option>
            <option>S080</option>
            <option>S081</option>
            <option>S082</option>
            <option>S083</option>
            <option>S084</option>
            <option>S085</option>
            <option>S086</option>
            <option>S087</option>
            <option>S088</option>
            <option>S089</option>
            <option>S090</option>
            <option>S091</option>
            <option>S092</option>
            <option>S093</option>
            <option>S094</option>
            <option>S095</option>
            <option>S096</option>
            <option>S097</option>
            <option>S098</option>
            <option>S099</option>
            <option>S100</option>
            <option>S101</option>
            <option>S102</option>
            <option>S103</option>
            <option>S104</option>
            <option>S105</option>
            <option>S106</option>
            <option>S107</option>
            <option>S108</option>
            <option>S109</option>
            <option>S110</option>
            <option>S111</option>
            <option>S112</option>
            <option>S113</option>
            <option>S114</option>
            <option>S115</option>
            <option>S116</option>
            <option>S117</option>
            <option>S118</option>
            <option>S119</option>
            <option>S120</option>
            <option>S121</option>
            <option>S122</option>
            <option>S123</option>
            <option>S124</option>
            <option>S125</option>
            <option>S126</option>
            <option>S127</option>
            <option>S128</option>
            <option>S129</option>
            <option>S130</option>
            <option>S131</option>
            <option>S132</option>
            <option>S133</option>
            <option>S134</option>
            <option>S135</option>
            <option>S136</option>
            <option>S137</option>
            <option>S138</option>
            <option>S139</option>
            <option>S140</option>
            <option>S141</option>
            <option>S142</option>
            <option>S143</option>
            <option>S144</option>
            <option>S145</option>
            <option>S146</option>
            <option>S147</option>
            <option>S148</option>
            <option>S149</option>
            <option>S150</option>
            <option>S151</option>
            <option>S152</option>
            <option>S153</option>
            <option>S154</option>
            <option>S155</option>
            <option>S156</option>
            <option>S157</option>
            <option>S158</option>
            <option>S159</option>
            <option>S160</option>
            <option>S161</option>
            <option>S162</option>
            <option>S163</option>
            <option>S164</option>
            <option>S165</option>
            <option>S166</option>
            <option>S167</option>
            <option>S168</option>
            <option>S169</option>
            <option>S170</option>
            <option>S171</option>
            <option>S172</option>
            <option>S173</option>
            <option>S174</option>
            <option>S175</option>
            <option>S176</option>
            <option>S177</option>
            <option>S178</option>
            <option>S179</option>
            <option>S180</option>
            <option>S181</option>
            <option>S182</option>
            <option>S183</option>
            <option>S184</option>
            <option>S185</option>
            <option>S186</option>
            <option>S187</option>
            <option>S188</option>
            <option>S189</option>
            <option>S190</option>
            <option>S191</option>
            <option>S192</option>
            <option>S193</option>
            <option>S194</option>
            <option>S195</option>
            <option>S196</option>
            <option>S197</option>
            <option>S198</option>
            <option>S199</option>
            <option>S200</option>
            <option>S201</option>
            <option>S202</option>
            <option>S203</option>
            <option>S204</option>
            <option>S205</option>
            <option>S206</option>
            <option>S207</option>
            <option>S208</option>
            <option>S209</option>
            <option>S210</option>
            <option>S211</option>
            <option>S212</option>
            <option>S213</option>
            <option>S214</option>
            <option>S215</option>
            <option>S216</option>
            <option>S217</option>
            <option>S218</option>
            <option>S219</option>
            <option>S220</option>
            <option>S221</option>
            <option>U001</option>
            <option>U002</option>
            <option>U003</option>
            <option>U004</option>
            <option>U005</option>
            <option>U006</option>
            <option>U007</option>
            <option>U008</option>
            <option>U009</option>
            <option>U010</option>
            <option>U011</option>
            <option>U012</option>
            <option>U013</option>
            <option>U014</option>
            <option>U015</option>
            <option>U016</option>
            <option>U017</option>
            <option>U018</option>
            <option>U019</option>
            <option>U020</option>
            <option>U021</option>
            <option>U022</option>
            <option>U023</option>
            <option>U024</option>
            <option>U025</option>
            <option>U026</option>
            <option>U027</option>
            <option>U028</option>
            <option>U029</option>
            <option>U030</option>
            <option>U031</option>
            <option>U032</option>
            <option>U033</option>
            <option>U034</option>
            <option>U035</option>
            <option>U036</option>
            <option>U037</option>
            <option>U038</option>
            <option>U039</option>
            <option>U040</option>
            <option>U041</option>
            <option>U042</option>
            <option>U043</option>
            <option>U044</option>
            <option>U045</option>
            <option>U046</option>
            <option>U047</option>
            <option>U048</option>
            <option>U049</option>
            <option>U050</option>
            <option>U051</option>
            <option>U052</option>
            <option>U053</option>
            <option>U054</option>
            <option>U055</option>
            <option>U056</option>
            <option>U057</option>
            <option>U058</option>
            <option>U059</option>
            <option>U060</option>
            <option>U061</option>
            <option>U062</option>
            <option>U063</option>
            <option>U064</option>
            <option>U065</option>
            <option>U066</option>
            <option>U067</option>
            <option>U068</option>
            <option>U069</option>
            <option>U070</option>
            <option>U071</option>
            <option>U072</option>
            <option>U073</option>
            <option>U074</option>
            <option>U075</option>
            <option>U076</option>
            <option>U077</option>
            <option>U078</option>
            <option>U079</option>
            <option>U080</option>
            <option>U081</option>
            <option>U082</option>
            <option>U083</option>
            <option>U084</option>
            <option>U085</option>
            <option>U086</option>
            <option>U087</option>
            <option>U088</option>
            <option>U089</option>
            <option>U090</option>
            <option>U091</option>
            <option>U092</option>
            <option>U093</option>
            <option>U094</option>
            <option>U095</option>
            <option>U096</option>
            <option>U097</option>
            <option>U098</option>
            <option>U099</option>
            <option>U100</option>
            <option>U101</option>
            <option>U102</option>
            <option>U103</option>
            <option>U104</option>
            <option>U105</option>
            <option>U106</option>
            <option>U107</option>
            <option>U108</option>
            <option>U109</option>
            <option>U110</option>
            <option>U111</option>
            <option>U112</option>
            <option>U113</option>
            <option>U114</option>
            <option>U115</option>
            <option>U116</option>
            <option>U117</option>
            <option>U118</option>
            <option>U119</option>
            <option>U120</option>
            <option>U121</option>
            <option>U122</option>
            <option>U123</option>
            <option>U124</option>
            <option>U125</option>
            <option>U126</option>
            <option>U127</option>
            <option>U128</option>
            <option>U129</option>
            <option>U130</option>
            <option>U131</option>
            <option>U132</option>
            <option>U133</option>
            <option>U134</option>
            <option>U135</option>
            <option>U136</option>
            <option>U137</option>
            <option>U138</option>
            <option>U139</option>
            <option>U140</option>
            <option>U141</option>
            <option>U142</option>
            <option>U143</option>
            <option>U144</option>
            <option>U145</option>
            <option>U146</option>
            <option>U147</option>
            <option>U148</option>
            <option>U149</option>
            <option>U150</option>
            <option>U151</option>
            <option>U152</option>
            <option>U153</option>
            <option>U154</option>
            <option>U155</option>
            <option>U156</option>
            <option>U157</option>
            <option>U158</option>
            <option>U159</option>
            <option>U160</option>
            <option>U161</option>
            <option>U162</option>
            <option>U163</option>
            <option>U164</option>
            <option>U165</option>
            <option>U166</option>
            <option>U167</option>
            <option>U168</option>
            <option>U169</option>
            <option>U170</option>
            <option>U171</option>
            <option>U172</option>
            <option>U173</option>
            <option>U174</option>
            <option>U175</option>
            <option>U176</option>
            <option>U177</option>
            <option>U178</option>
            <option>U179</option>
            <option>U180</option>
            <option>U181</option>
            <option>U182</option>
            <option>U183</option>
            <option>U184</option>
            <option>U185</option>
            <option>U186</option>
            <option>U187</option>
            <option>U188</option>
            <option>U189</option>
            <option>U190</option>
            <option>U191</option>
            <option>U192</option>
            <option>U193</option>
            <option>U194</option>
            <option>U195</option>
            <option>U196</option>
            <option>U197</option>
            <option>U198</option>
            <option>U199</option>
            <option>U200</option>
            <option>U201</option>
            <option>U202</option>
            <option>U203</option>
            <option>U204</option>
            <option>U205</option>
            <option>U206</option>
            <option>U207</option>
            <option>U208</option>
            <option>U209</option>
            <option>U210</option>
            <option>U211</option>
            <option>U212</option>
            <option>U213</option>
            <option>U214</option>
            <option>U215</option>
            <option>U216</option>
            <option>U217</option>
            <option>U218</option>
            <option>U219</option>
            <option>U220</option>
            <option>U221</option>
            <option>U222</option>
            <option>U223</option>
            <option>U224</option>
            <option>U225</option>
            <option>U226</option>
            <option>U227</option>
            <option>U228</option>
            <option>U229</option>
            <option>U230</option>
            <option>U231</option>
            <option>U232</option>
            <option>U233</option>
            <option>U234</option>
            <option>U235</option>
            <option>U236</option>
            <option>U237</option>
            <option>U238</option>
            <option>U239</option>
            <option>U240</option>
            <option>U241</option>
            <option>U242</option>
            <option>U243</option>
            <option>U244</option>
            <option>U245</option>
            <option>U246</option>
            <option>U247</option>
            <option>U248</option>
            <option>U249</option>
            <option>U250</option>
            <option>U251</option>
            <option>U252</option>
            <option>U253</option>
            <option>U254</option>
            <option>U255</option>


        </select>
    </div>

    <div class="form-group">
        <label for="Operador">Operador</label>
        <select name="Operador" class="form-control">
            <option selected>Por favor elija el operador correcto al cual pertenece el Bus</option>
            <option>Ciudad Movil</option>
            <option>Connexion Movil</option>
            <option>GMovil</option>
            <option>Express Del Futuro</option>
            <option>Consorcio Express</option>
            <option>Transmasivo</option>
            <option>Somos K</option>
            <option>Metrobus</option>
            <option>SI 99</option>
        </select>
    </div>

    <div class="form-group">
        <label for="Modelo">Modelo del Bus</label>
        <select name="Modelo" class="form-control">
        <option selected>Por Favor Elija el modelo adecuado</option>
            <option>Gran Viale</option>
            <option>Viale</option>
            <option>Gran Viale BRT</option>
            <option>Gran Viale BRS</option>
            <option>Urbanuss Pluss</option>
            <option>Urbanuss Pluss S3</option>
            <option>BYD</option>
            <option>Doppio</option>

        </select>

    </div>



    <div class="form-group">
        <label for="Carroceria">Marca</label>
        <select name="Carroceria" class="form-control">
            <option selected>Por Elija la marca correcta de la carroceria del Bus</option>
            <option>Marcopolo</option>
            <option>Comil</option>
            <option>Busscar</option>
            <option>BYD</option>
        </select>
    </div>


    <div class="form-group">
        <label for="Marca">Motor y Potencia del Camion</label>
        <select name="Marca" class="form-control">
            <option selected>Por Favor Elija la marca adecuada y potencia</option>
            <option>Volvo B10M</option>
            <option>Volvo B12M</option>
            <option>Volvo B340M</option>
            <option>Mercedes Benz UPA-400</option>
            <option>Mercedes Benz OM-457-LA</option>
            <option>Scania L94</option>
            <option>Scania K250</option>
            <option>Scania F340-HA</option>
        </select>
    </div>

    <div class="form-group">
        <label for="Tipologia">Tipologia del Bus</label>
        <select name="Tipologia" class="form-control">
            <option selected>Por Favor Elija la tipologia adecuada</option>
            <option>Bus Padron Dual</option>
            <option>Articulado</option>
            <option>Biarticulado</option>
        </select>
    </div>

    </hr>

    <div class="text-right">
        <button type="submit" name="AgregarUsuario" value="Guardar" class="btn btn-primary">Agregar Usuario</button>
    </div>

</form>

<script>
    $(document).ready(function(){
        $("#frm-alumno").submit(function(){
            return $(this).validate();
        });
    })
</script>